AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: All the RAG backend for AWS lambda via AWS SAM

Parameters:
  StageName:
    Type: String
    Default: prod
    Description: API Gateway stage name (should always be prod)
  BaseUrl:
    Type: String
    Description: URL for the completion provider api
  BucketName:
    Type: String
    Description: Bucket name for the S3 Vectors bucket
  CompletionModel:
    Type: String
    Description: Name of the completion model
  CompletionProvider:
    Type: String
    Description: Name of completion provider service
  EmbeddingModel:
    Type: String
    Description: Embedding model name
  IndexName:
    Type: String
    Description: S3 Vectors index name
  ProfileName:
    Type: String
    Description: AWS Profile name (for auth, do I need this here?)
  ProfileRegion:
    Type: String
    Description: AWS Region


Globals:
  Function:
    Runtime: python3.12
    Timeout: 30
    MemorySize: 512
    Architectures:
      - x86_64
    Environment:
      Variables:
        FLASK_ENV: production


Resources:
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod 
      EndpointConfiguration: REGIONAL
      Cors:
        AllowMethods: "'GET,POST,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization'"
        AllowOrigin: "'*'"

  FlaskFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: backend.lambda_handler
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - bedrock: InvokeModel
              Resource:
                - !Sub arn:aws:bedrock:${AWS::Region}::foundation-model/*
      Events:
        SendMessage:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /send_message
            Method: POST
        GetMessage:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /get_message
            Method: GET
      Environment:
        Variables:
          API_KEY: ""
          BASE_URL: !Ref BaseUrl
          BUCKET_NAME: !Ref BucketName
          COMPLETION_MODEL: !Ref CompletionModel
          COMPLETION_PROVIDER: !Ref CompletionProvider
          EMBEDDING_MODEL: !Ref EmbeddingModel
          INDEX_NAME: !Ref IndexName
          LOG_LEVEL: "info"
          PROFILE_NAME: !Ref ProfileName
          PROFILE_REGION: !Ref ProfileRegion
          SECRET_KEY: ""
          VDB: "Amazon S3 Vector"
    MetaData:
      BuildMethod: python3.12

Outputs:
  ApiUrl:
    Description: Base URL for the API Gateway stage.
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/{StageName}"
  SendMessageUrl:
    Description: POST /send_message endpoint
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/{StageName}/send_message"
  GetMessageUrl:
    Description: GET /get_message endpoint
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/{StageName}/get_message"
