# yaml-language-server: $schema=https://raw.githubusercontent.com/aws/serverless-application-model/main/samtranslator/schema/schema.json

AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: All the RAG backend for AWS lambda via AWS SAM

Parameters:
  StageName:
    Type: String
    Default: prod
    Description: API Gateway stage name (should always be prod)
  BaseUrl:
    Type: String
    Description: URL for the completion provider api
  BucketName:
    Type: String
    Description: Bucket name for the S3 Vectors bucket
  BucketNumber:
    Type: String
    Description: The number associated with the S3 vectors bucket
  CompletionModel:
    Type: String
    Description: Name of the completion model
  CompletionProvider:
    Type: String
    Description: Name of completion provider service
  EmbeddingModel:
    Type: String
    Description: Embedding model name
  IndexName:
    Type: String
    Description: S3 Vectors index name
  ProfileName:
    Type: String
    Description: AWS Profile name (for auth, do I need this here?)
  ProfileRegion:
    Type: String
    Description: AWS Region

Globals:
  Function:
    Runtime: python3.12
    Timeout: 30
    MemorySize: 512
    Architectures:
      - x86_64
    Environment:
      Variables:
        FLASK_ENV: production

Resources:
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Sub ${StageName}
      EndpointConfiguration: REGIONAL
      Cors:
        AllowMethods: "'GET,POST,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization'"
        AllowOrigin: "'*'"

  ATRStreamFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: backend.lambda_handler
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
              Resource:
                - !Sub arn:aws:bedrock:${AWS::Region}::foundation-model/*
            - Effect: Allow
              Action:
                - s3vectors:QueryVectors
                - s3vectors:GetVectors
              Resource:
                - !Sub arn:aws:s3vectors:${AWS::Region}:${BucketNumber}:bucket/${BucketName}/index/${IndexName}

      FunctionUrlConfig:
        AuthType: NONE
        InvokeMode: RESPONSE_STREAM
        Cors:
          AllowOrigins: ["*"]
          AllowHeaders: ["*"]
          AllowMethods: ["*"]
      Environment:
        Variables:
          API_KEY: ""
          BASE_URL: !Ref BaseUrl
          BUCKET_NAME: !Ref BucketName
          COMPLETION_MODEL: !Ref CompletionModel
          COMPLETION_PROVIDER: !Ref CompletionProvider
          EMBEDDING_MODEL: !Ref EmbeddingModel
          INDEX_NAME: !Ref IndexName
          LOG_LEVEL: "info"
          PROFILE_NAME: !Ref ProfileName
          PROFILE_REGION: !Ref ProfileRegion
          SECRET_KEY: ""
          VDB: "Amazon S3 Vector"

  ATRFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: backend.lambda_handler
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
              Resource:
                - !Sub arn:aws:bedrock:${AWS::Region}::foundation-model/*
            - Effect: Allow
              Action:
                - s3vectors:QueryVectors
                - s3vectors:GetVectors
              Resource:
                - !Sub arn:aws:s3vectors:${AWS::Region}:${BucketNumber}:bucket/${BucketName}/index/${IndexName}

      Events:
        GetHistory:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /chat_history
            Method: GET
        Register:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /register
            Method: GET
        Login:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /login
            Method: GET
        PastChats:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /past_chats
            Method: GET
      Environment:
        Variables:
          API_KEY: ""
          BASE_URL: !Ref BaseUrl
          BUCKET_NAME: !Ref BucketName
          COMPLETION_MODEL: !Ref CompletionModel
          COMPLETION_PROVIDER: !Ref CompletionProvider
          EMBEDDING_MODEL: !Ref EmbeddingModel
          INDEX_NAME: !Ref IndexName
          LOG_LEVEL: "info"
          PROFILE_NAME: !Ref ProfileName
          PROFILE_REGION: !Ref ProfileRegion
          SECRET_KEY: ""
          VDB: "Amazon S3 Vector"
    MetaData:
      BuildMethod: python3.12

  ATRRedirect:
    Type: AWS::Serverless::Api
    Properties:
      Cors:
        AllowOrigin: ["*"]
        AllowHeaders: ["*"]
        AllowMethods: ["*"]
      StageName: !Sub ${StageName}
      DefinitionBody:
        swagger: "2.0"
        info:
          title: "Redirect to Streaming Lambda url"
          version: "1.0"
        basePath: "/"
        schemes:
          - https
        paths:
          /send_message:
            post:
              produces:
                - text/event-stream
              responses:
                "302":
                  description: "Redirect"
                  headers:
                    Location:
                      type: "string"
              x-amazon-apigateway-integration:
                type: mock
                requestTemplates:
                  # text/event-stream: '{"statusCode": 302}'
                  application/json: '{"statusCode": 302}'
                responses:
                  default:
                    statusCode: "302"
                    responseParameters:
                      method.response.header.Location:
                        Fn::Sub: "'${ATRStreamFunctionUrl.FunctionUrl}'"
                passthroughBehavior: "when_no_match"

Outputs:
  ATRStreamFunctionArn:
    Value: !GetAtt ATRStreamFunction.Arn
  ATRStreamFunctionUrl:
    Value: !GetAtt ATRStreamFunctionUrl.FunctionUrl
    Description: Public Function url with response streaming enabled
  ApiUrl:
    Description: Base URL for the API Gateway stage.
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/{StageName}"
  RegisterUrl:
    Description: POST /register endpoint
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/{StageName}/register"
  LoginUrl:
    Description: POST /login endpoint
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/{StageName}/login"
  PastChatsUrl:
    Description: GET /past_chats endpoint
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/{StageName}/past_chats"
  ChatHistroyUrl:
    Description: GET /chat_history endpoint
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/{StageName}/chat_history"
