# yaml-language-server: $schema=https://raw.githubusercontent.com/aws/serverless-application-model/main/samtranslator/schema/schema.json

AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: All the RAG backend for AWS lambda via AWS SAM

Parameters:
  StageName:
    Type: String
    Default: prod
    Description: API Gateway stage name (should always be prod)
  BaseUrl:
    Type: String
    Description: URL for the completion provider api
  BucketName:
    Type: String
    Description: Bucket name for the S3 Vectors bucket
  BucketNumber:
    Type: String
    Description: The number associated with the S3 vectors bucket
  CompletionModel:
    Type: String
    Description: Name of the completion model
  CompletionProvider:
    Type: String
    Description: Name of completion provider service
  DatabaseURL:
    Type: String
    Description: URL of the database to connect to
  EmbeddingModel:
    Type: String
    Description: Embedding model name
  FrontendURL:
    Type: String
    Description: URL for the frontend, used for CORS
  IndexName:
    Type: String
    Description: S3 Vectors index name
  LogLevel:
    Type: String
    Description: Backend log level
  ProfileName:
    Type: String
    Description: AWS Profile name (for auth, do I need this here?)
  ProfileRegion:
    Type: String
    Description: AWS Region
  SupabaseURL:
    Type: String
    Description: Supabase URL for auth
  UseCors:
    Type: String
    Description: CORS toggle for compatibility with services that do/do not do this for you
  VDB:
    Type: String
    Description: Vector database driver to use

Globals:
  Function:
    Runtime: python3.12
    Timeout: 30
    MemorySize: 512
    Architectures:
      - x86_64
    Environment:
      Variables:
        FLASK_ENV: production

Resources:
  ATRStreamFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: startup.sh
      Layers:
        - !Sub arn:aws:lambda:${AWS::Region}:753240598075:layer:LambdaAdapterLayerX86:25
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
              Resource:
                - !Sub arn:aws:bedrock:${AWS::Region}::foundation-model/*
            - Effect: Allow
              Action:
                - s3vectors:QueryVectors
                - s3vectors:GetVectors
              Resource:
                - !Sub arn:aws:s3vectors:${AWS::Region}:${BucketNumber}:bucket/${BucketName}/index/${IndexName}

      FunctionUrlConfig:
        AuthType: NONE
        InvokeMode: RESPONSE_STREAM
        Cors:
          AllowCredentials: false
          AllowOrigins:
            - !Sub ${FrontendURL}
          AllowHeaders: ["*"]
          AllowMethods: ["*"]
      Environment:
        Variables:
          AWS_LAMBDA_EXEC_WRAPPER: /opt/bootstrap
          PORT: "3459"
          AWS_LWA_READINESS_CHECK_PATH: /health_check
          AWS_LWA_READINESS_CHECK_PORT: "3459"
          READINESS_CHECK_PATH: /example_page
          AWS_LWA_INVOKE_MODE: RESPONSE_STREAM
          API_KEY: ""
          BASE_URL: !Ref BaseUrl
          BUCKET_NAME: !Ref BucketName
          COMPLETION_MODEL: !Ref CompletionModel
          COMPLETION_PROVIDER: !Ref CompletionProvider
          DATABASE_URL: !Ref DatabaseURL
          EMBEDDING_MODEL: !Ref EmbeddingModel
          INDEX_NAME: !Ref IndexName
          LOG_LEVEL: !Ref LogLevel
          PROFILE_NAME: !Ref ProfileName
          PROFILE_REGION: !Ref ProfileRegion
          SECRET_KEY: ""
          SUPABASE_URL: !Ref SupabaseURL
          USE_CORS: !Ref UseCors
          VDB: !Ref VDB

  ATRStreamFunctionUrlInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunctionUrl
      FunctionName: !Ref ATRStreamFunction
      Principal: "*"
      FunctionUrlAuthType: NONE

  ATRStreamFunctionCoreInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref ATRStreamFunction
      Principal: "*"
      InvokedViaFunctionUrl: true

  # ATRFunction:
  #   Type: AWS::Serverless::Function
  #   Properties:
  #     CodeUri: src/
  #     Handler: startup.sh
  #     Layers:
  #       - !Sub arn:aws:lambda:${AWS::Region}:753240598075:layer:LambdaAdapterLayerX86:25
  #     Policies:
  #       - Statement:
  #           - Effect: Allow
  #             Action:
  #               - bedrock:InvokeModel
  #             Resource:
  #               - !Sub arn:aws:bedrock:${AWS::Region}::foundation-model/*
  #           - Effect: Allow
  #             Action:
  #               - s3vectors:QueryVectors
  #               - s3vectors:GetVectors
  #             Resource:
  #               - !Sub arn:aws:s3vectors:${AWS::Region}:${BucketNumber}:bucket/${BucketName}/index/${IndexName}
  #
  #     Events:
  #       GetHistory:
  #         Type: HttpApi
  #         Properties:
  #           # RestApiId: !Ref ApiGateway
  #           Path: /chat_history
  #           Method: GET
  #       Register:
  #         Type: HttpApi
  #         Properties:
  #           # RestApiId: !Ref ApiGateway
  #           Path: /register
  #           Method: POST
  #       Login:
  #         Type: HttpApi
  #         Properties:
  #           # RestApiId: !Ref ApiGateway
  #           Path: /login
  #           Method: POST
  #       PastChats:
  #         Type: HttpApi
  #         Properties:
  #           # RestApiId: !Ref ApiGateway
  #           Path: /past_chats
  #           Method: GET
  #       HealthCheck:
  #         Type: HttpApi
  #         Properties:
  #           Path: /health_check
  #           Method: GET
  #     Environment:
  #       Variables:
  #         AWS_LAMBDA_EXEC_WRAPPER: /opt/bootstrap
  #         PORT: "3459"
  #         AWS_LWA_READINESS_CHECK_PORT: "3459"
  #         AWS_LWA_READINESS_CHECK_PATH: /health_check
  #         AWS_LWA_READ_TIMEOUTE: "10"
  #         AWS_LWA_WRITE_TIMEOUTE: "10"
  #         API_KEY: ""
  #         BASE_URL: !Ref BaseUrl
  #         BUCKET_NAME: !Ref BucketName
  #         COMPLETION_MODEL: !Ref CompletionModel
  #         COMPLETION_PROVIDER: !Ref CompletionProvider
  #         EMBEDDING_MODEL: !Ref EmbeddingModel
  #         INDEX_NAME: !Ref IndexName
  #         LOG_LEVEL: "info"
  #         PROFILE_NAME: !Ref ProfileName
  #         PROFILE_REGION: !Ref ProfileRegion
  #         SECRET_KEY: ""
  #         VDB: "Amazon S3 Vector"
  #   MetaData:
  #     BuildMethod: python3.12

  # ATRRedirect:
  #   Type: AWS::Serverless::HttpApi
  #   Properties:
  #     CorsConfiguration:
  #       AllowCredentials: false
  #       AllowOrigins:
  #         - !Sub ${FrontendURL}
  #       AllowHeaders:
  #         - "*"
  #     # Cors:
  #     #   AllowCredentials: false
  #     #   AllowOrigin: ["*"]
  #     #   AllowHeaders: ["*"]
  #     #   AllowMethods: ["*"]
  #     StageName: !Sub ${StageName}
  #     DefinitionBody:
  #       openapi: "3.0.3"
  #       info:
  #         title: "Redirect to Streaming Lambda url"
  #         version: "1.0"
  #       paths:
  #         /send_message:
  #           post:
  #             responses:
  #               "308":
  #                 description: "Redirect"
  #                 headers:
  #                   Location:
  #                     schema:
  #                       type: "string"
  #                 content:
  #                   text/event-stream:
  #                     schema:
  #                       type: string
  #             x-amazon-apigateway-integration:
  #               type: mock
  #               requestTemplates:
  #                 # text/event-stream: '{"statusCode": 308}'
  #                 application/json: '{"statusCode": 308}'
  #               responses:
  #                 default:
  #                   statusCode: "308"
  #                   responseParameters:
  #                     method.response.header.Location:
  #                       Fn::Sub: "'${ATRStreamFunctionUrl.FunctionUrl}'"
  #               passthroughBehavior: "when_no_match"

Outputs:
  # ATRStreamFunctionArn:
  #   Value: !GetAtt ATRStreamFunction.Arn
  ATRStreamFunctionUrl:
    Value: !GetAtt ATRStreamFunctionUrl.FunctionUrl
    Description: Public Function url with response streaming enabled
