"""Initial revision

Revision ID: bd1c9611be00
Revises: 
Create Date: 2025-12-05 11:45:48.696414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd1c9611be00'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('issuer', sa.String(length=255), nullable=False),
    sa.Column('sub', sa.String(length=255), nullable=False),
    sa.Column('user_prompt', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('issuer', 'sub')
    )
    op.create_table('chat',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_issuer', sa.String(length=255), nullable=False),
    sa.Column('user_sub', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_issuer', 'user_sub'], ['user.issuer', 'user.sub'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contents', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=False),
    sa.Column('chat_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    op.drop_table('chat')
    op.drop_table('user')
    # ### end Alembic commands ###
